"""咕咕嘎嘎 AI-VTuber — 浅色预设主题

清爽浅色主题，适合明亮环境。
"""

from ..definitions import ThemeDefinition
from gugu_native.themes.style_types import (
    BorderRadiusStyle, SpacingStyle, ShadowStyle, TypographyStyle, ControlStyle
)

LIGHT_THEME = ThemeDefinition(
    id="light",
    name="浅色",
    description="经典浅色主题，清爽明亮",
    base_mode="light",
    preview_colors=["#f0f2f5", "#4263eb", "#7c3aed"],
    colors={
        "window_bg": "#f0f2f5",
        "sidebar_bg": "#e8eaed",
        "card_bg": "#ffffff",
        "card_bg_hover": "#f8f9fa",
        "card_border": "#e0e2e8",
        "card_border_hover": "#c8cad2",
        "chat_bg": "#f0f2f5",
        "ai_bubble_bg": "#ffffff",
        "ai_bubble_border": "#dee2e6",
        "ai_bubble_accent": "#7c3aed",
        "user_bubble_bg": "#4263eb",
        "user_bubble_border": "#5c7cfa",
        "user_bubble_accent": "#5c7cfa",
        "user_text_color": "#ffffff",
        "system_msg_color": "#868e96",
        "skeleton_color": "#e9ecef",
        "skeleton_shimmer": "#f1f3f5",
        "chat_timestamp_bg": "#e9ecef",
        "chat_timestamp_border": "#dee2e6",
        "chat_group_gap": "12px",
        "chat_same_gap": "4px",
        "chat_bubble_max_width": "80%",
        "chat_avatar_size": "34",
        "chat_bubble_padding": "10px 16px",
        "chat_bubble_radius_ai": "12px",
        "chat_bubble_radius_user": "12px",
        "chat_typing_cursor_color": "#4263eb",
        "text_primary": "#1a1a2e",
        "text_secondary": "#555566",
        "text_muted": "#9a9aaa",
        "text_on_accent": "#ffffff",
        "accent": "#4263eb",
        "accent_hover": "#3b5bdb",
        "accent_pressed": "#3549c6",
        "accent_gradient_start": "#5c7cfa",
        "accent_gradient_end": "#4263eb",
        "success": "#37b24d",
        "success_bg": "#d3f9d8",
        "warning": "#f59f00",
        "warning_bg": "#fff3bf",
        "error": "#f03e3e",
        "error_bg": "#ffe0e0",
        "info": "#4263eb",
        "info_bg": "#e7eef8",
        "stat_working": "#4dabf7",
        "stat_episodic": "#69db7c",
        "stat_semantic": "#da77f2",
        "stat_facts": "#ffd43b",
        "stat_forgotten": "#868e96",
        "input_bg": "#ffffff",
        "input_border": "#d0d2d8",
        "input_focus_border": "#4263eb",
        "input_focus_shadow": "rgba(66,99,235,0.15)",
        "log_bg": "#f8f9fa",
        "log_text": "#212529",
        "log_timestamp": "#868e96",
        "log_success": "#37b24d",
        "log_error": "#f03e3e",
        "log_info": "#4dabf7",
        "progress_start": "#4263eb",
        "progress_end": "#7c3aed",
        "shadow_sm": "rgba(0,0,0,0.06)",
        "shadow_md": "rgba(0,0,0,0.10)",
        "shadow_lg": "rgba(0,0,0,0.15)",
        "shadow_xl": "rgba(0,0,0,0.20)",
        "timestamp_color": "#868e96",
        "divider": "#e0e2e8",
    },
    border_radius=BorderRadiusStyle.from_preset("soft"),
    spacing=SpacingStyle.from_preset("comfortable"),
    shadow=ShadowStyle.from_preset("flat"),
    typography=TypographyStyle.from_preset("msyh"),
    controls=ControlStyle.from_preset("outline"),
)
