"""咕咕嘎嘎 AI-VTuber — 海洋预设主题

深蓝色调暗色主题，灵感来自深海。
"""

from ..definitions import ThemeDefinition
from gugu_native.themes.style_types import (
    BorderRadiusStyle, SpacingStyle, ShadowStyle, TypographyStyle, ControlStyle
)

OCEAN_THEME = ThemeDefinition(
    id="ocean",
    name="海洋",
    description="深邃的海洋蓝色调，冷静沉稳",
    base_mode="dark",
    preview_colors=["#0f1a2e", "#1971c2", "#1c7ed6"],
    colors={
        "window_bg": "#0f1a2e",
        "sidebar_bg": "#0a1422",
        "card_bg": "#152238",
        "card_bg_hover": "#1a2a44",
        "card_border": "#1e3350",
        "card_border_hover": "#264060",
        "chat_bg": "#0f1a2e",
        "ai_bubble_bg": "#152238",
        "ai_bubble_border": "#1e3350",
        "ai_bubble_accent": "#1971c2",
        "user_bubble_bg": "#1971c2",
        "user_bubble_border": "#1c7ed6",
        "user_bubble_accent": "#1c7ed6",
        "user_text_color": "#ffffff",
        "system_msg_color": "#6c7a8a",
        "skeleton_color": "#152238",
        "skeleton_shimmer": "#1a2a44",
        "chat_timestamp_bg": "#0a1422",
        "chat_timestamp_border": "#1e3350",
        "chat_group_gap": "12px",
        "chat_same_gap": "4px",
        "chat_bubble_max_width": "80%",
        "chat_avatar_size": "34",
        "chat_bubble_padding": "10px 16px",
        "chat_bubble_radius_ai": "12px",
        "chat_bubble_radius_user": "12px",
        "chat_typing_cursor_color": "#1971c2",
        "text_primary": "#e0e8f0",
        "text_secondary": "#8a9ab0",
        "text_muted": "#5a6a78",
        "text_on_accent": "#ffffff",
        "accent": "#1971c2",
        "accent_hover": "#1565c0",
        "accent_pressed": "#1250a0",
        "accent_gradient_start": "#1c7ed6",
        "accent_gradient_end": "#1971c2",
        "success": "#2e9e5a",
        "success_bg": "#1a3028",
        "warning": "#e6a817",
        "warning_bg": "#30281a",
        "error": "#d93030",
        "error_bg": "#301a1a",
        "info": "#1971c2",
        "info_bg": "#1a2430",
        "stat_working": "#4d9bd7",
        "stat_episodic": "#5ecc70",
        "stat_semantic": "#da77f2",
        "stat_facts": "#ffd43b",
        "stat_forgotten": "#6c7a8a",
        "input_bg": "#122030",
        "input_border": "#1e3350",
        "input_focus_border": "#1971c2",
        "input_focus_shadow": "rgba(25,113,194,0.25)",
        "log_bg": "#0a1422",
        "log_text": "#c9d1d9",
        "log_timestamp": "#5a6a78",
        "log_success": "#2e9e5a",
        "log_error": "#d93030",
        "log_info": "#1971c2",
        "progress_start": "#1971c2",
        "progress_end": "#4d9bd7",
        "shadow_sm": "rgba(0,0,0,0.20)",
        "shadow_md": "rgba(0,0,0,0.30)",
        "shadow_lg": "rgba(0,0,0,0.40)",
        "shadow_xl": "rgba(0,0,0,0.50)",
        "timestamp_color": "#5a6a78",
        "divider": "#1e3350",
    },
    border_radius=BorderRadiusStyle.from_preset("soft"),
    spacing=SpacingStyle.from_preset("compact"),
    shadow=ShadowStyle.from_preset("flat"),
    typography=TypographyStyle.from_preset("msyh"),
    controls=ControlStyle.from_preset("outline"),
)
